name: Publish features
on:
  push:
    branches: "main"
    paths-ignore:
      - .gitignore
      - LICENSE
      - README.md
      - .gitattributes
      - .github/**
      - "!.github/workflows/publish-features.yml"
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true
jobs:
  publish-features:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - run: npm install -g @devcontainers/cli
      - run: devcontainer features --help
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
