name: Test relevant features
on:
  push:
    branches: "main"
    paths-ignore:
      - .gitignore
      - LICENSE
      - README.md
      - .gitattributes
  pull_request:
    paths-ignore:
      - .gitignore
      - LICENSE
      - README.md
      - .gitattributes
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  list-features:
    outputs:
      features: ${{ steps.list-features-outputs.features }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: list-features
        uses: devcontainers-community/list-features@v1
  test-feature:
    needs: list-features
    strategy:
      fail-fast: false
      matrix: ${{ toJSON(needs.list-features.outputs.features) }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm install -g @devcontainers/cli
      - run: devcontainer features test -f ${{ matrix.id }}
