name: Update readmes
on:
  push:
    branches: "main"
    paths-ignore:
      - .gitignore
      - LICENSE
      - README.md
      - .gitattributes
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true
jobs:
  list-features:
    outputs:
      changed-features: ${{ steps.list-features-outputs.changed-features }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: list-features
        uses: devcontainers-community/list-features@v1
  update-feature-readme:
    needs: list-features
    concurrency: ${{ github.workflow }}-write
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.list-features.outputs.changed-features) }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: devcontainers-community/update-feature-readme@v1
        with:
          feature-id: ${{ matrix.id }}
      - uses: stefanzweifel/git-auto-commit-action@v4
